version: '3'

networks:
  monitoring:
    driver: bridge
  common:
    driver: bridge

services:
  item-keeper:
    build:
      dockerfile: ./item-keeper/Dockerfile
    container_name: item-keeper
    volumes:
      - item_keeper_data:/mapping_configs
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - QUARTZ_CRON_EXPRESSION=${QUARTZ_CRON_EXPRESSION}
    depends_on:
      postgres:
          condition: service_healthy
    networks:
      - monitoring
      - common
  item-keeper-admin:
    build:
      dockerfile: ./item-keeper-admin/Dockerfile
    container_name: item-keeper-admin
    ports:
      - "8081:8081"
    environment:
      - GRAPHQL_CLIENT_URL=http://item-keeper:8080/graphql
    networks:
      - common
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "9095:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - prometheus
    networks:
      - monitoring
    volumes:
      - grafana_storage:/var/lib/grafana
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - common
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - monitoring
      - common

volumes:
  item_keeper_data:
  grafana_storage:
