apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'postgres-exporter'
        static_configs:
          - targets: [ 'postgres-exporter:9187' ]
      - job_name: 'item-keeper-metrics'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'item-keeper:8080' ]
kind: ConfigMap
metadata:
  name: prometheus-configmap
